#!/bin/bash

# Source all the bash files.

source_bash_files() {
    declare -r CURRENT_DIRECTORY="$(pwd)"

    declare -r -a FILES_TO_SOURCE=(
        "bash_aliases"
        "bash_autocomplete"
        "bash_exports"
        "bash_functions"
        "bash_options"
        "bash_prompt"
        "bash.local"
    )

    local file=""
    local i=""

    for i in ${!FILES_TO_SOURCE[*]}; do
        file="$HOME/.${FILES_TO_SOURCE[$i]}"

        [ -r "$file" ] \
            && . "$file"
    done

    cd "$CURRENT_DIRECTORY"
}

source_bash_files
unset -f source_bash_files

# Run the SSH agent so you don't have to type your passphrase constantly.

env=~/.ssh/agent.env

agent_load_env() {
    if [ -f "$env" ]; then
        . "$env" >| /dev/null
    fi
}

agent_start() {
    (umask 077; ssh-agent >| "$env")
    . "$env" >| /dev/null
}

agent_load_env

# agent_run_state:
#   0 = agent running w/ key
#   1 = agent running w/o key
#   2 = agent not running
agent_run_state=$(ssh-add -l >| /dev/null 2>&1; echo $?)

if [ ! "$SSH_AUTH_SOCK" ] || [ $agent_run_state = 2 ]; then
    agent_start
    ssh-add
elif [ "$SSH_AUTH_SOCK" ] && [ $agent_run_state = 1 ]; then
    ssh-add
fi

unset agent_run_state env
unset -f agent_load_env agent_start
