#!/bin/bash

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

alias c="clear"
alias g="git"
alias m="man"
alias n="npm"
alias w="cd $HOME/workspace"

# apt

alias apti="sudo apt install"
alias aptr="sudo apt remove"
alias apts="sudo apt search"
alias aptu="sudo apt update && sudo apt upgrade"

# Update applications and CLTs

alias u="sudo apt update \
            && sudo apt upgrade \
            && npm install --global npm \
            && npm upgrade --global"
