#!/bin/bash

# Readline configuration
# http://ss64.com/bash/syntax-inputrc.html

# Disable beeping and window flashing.
set bell-style none

# User case-insensitive tab autocompletion.
set completion-ignore-case on
